{ inputs, ... }:
{
    flake.modules.nixos.nire-durandal = {
        modulesPath,
        config,
        lib,
        nix-index-database,
        ...
    }:
    {
        imports = with inputs.self.modules.nixos; [
            nix-index-database.nixosModules.nix-index
            (inputs.import-tree ./hw-conf)
            (inputs.import-tree ./fixes)
        ];

    
      nixpkgs.hostPlatform = "x86_64-linux";
      system.stateVersion = "23.11"; # Don't change. https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion
      networking.hostName = "nire-durandal";

      imports = [
        
        # hw-conf/ contains the hardware-configuration.nix generated by nixos-generate-config.
        # fixes/ contains any hardware-specific patches or workarounds.
        (inputs.import-tree ./hw-conf)
        (inputs.import-tree ./fixes)
      ];
    };
    }
}
