keys:
  - &nire-durandal age19klcl9s2vlhnvgae2nhukl2ypwlq0054htgf7jpyxee2wfprmyjqdl7sfg
  - &nire-lysithea age1j56xctqgpp7sgay4yta7g47rusr54kxv8nk0r9tvlpf8jxffg4jqu6qrzf
  - &nire-tenacity age125j57asy9he50au73pjhddw8nl3s30yj8e9e2r7qe3v428nl7fnqn09c7ksvvuuv94gw99fwqz630m5hlcw2kdr4acdjspztnlr55xq3h0af3

                    
creation_rules:
  # - path_regex: ./secrets.yaml$
  - path: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-durandal
          - *nire-lysithea
          - *nire-tenacity
  # - path_regex: <user>/secrets.yaml$             # if you want user-specific configs 
    # key_groups:
      # - age:
          # - *nire-durandal
          # - *nire-galatea
          # - *nire-lysithea
