keys:
  - &nire-durandal age19klcl9s2vlhnvgae2nhukl2ypwlq0054htgf7jpyxee2wfprmyjqdl7sfg
  - &nire-lysithea age1a3h0396j3h3925rzlhqvwhpkm909zzswkcww4e6y502xm8n7wyfsuy7cre
  - &nire-tenacity age1x9pg09dcppkdp33lcfsnzj6lryf3h3s07nu9uv5d5kkwc3j4zpmq5x9rwj 
creation_rules:
  # - path_regex: ./secrets.yaml$
  - path: ./secrets.yaml$
    key_groups:
      - age:
          - *nire-durandal
          - *nire-lysithea
          - *nire-tenacity
  # - path_regex: <user>/secrets.yaml$             # if you want user-specific configs 
    # key_groups:
      # - age:
          # - *nire-durandal
          # - *nire-galatea
          # - *nire-lysithea
