{ 
    ... 
}: 
{
  imports = [
    ./appearance-cli
    ./command-runners
    ./dev
    ./editors
    ./file-info
    ./file-transfer
    ./help-systems
    ./input
    ./interpreters
    ./multiplexers
    ./navigation
    ./nix-util
    ./package-management
    ./search-utils
    ./shell
    ./shell-history
    ./shell-specific
    ./storage-stats
    ./sysadmin
    ./system-stats
    ./text-manip
    ./text-viewers
  ];
}
