# Flake outputs — receives the evaluated inputs attrset from flake.nix.
# flake.nix is auto-generated by flake-file; edit flake-config.nix and run
# `nix run .#write-flake` to regenerate it. This file is NOT auto-generated.
inputs:
inputs.flake-parts.lib.mkFlake { inherit inputs; } {
  imports = [
    # den: provides the `den.aspects` option used throughout configs/ to declare
    # reusable NixOS/home-manager modules in a dendritic pattern.
    inputs.den.flakeModule

    # flake-aspects: transposes den.aspects.X.nixos  → flake.modules.nixos.X
    #                            den.aspects.X.homeManager → flake.modules.homeManager.X
    inputs.flake-aspects.flakeModule

    # flake-file: provides the `write-flake` app that regenerates flake.nix.
    inputs.flake-file.flakeModules.default

    # Recursively imports every .nix file under configs/, picking up all
    # den.aspects declarations for system-config and home-manager.
    (inputs.import-tree ./configs)

    # Declares which CPU architectures this flake supports (x86_64-linux, aarch64-darwin).
    ./system-archs.nix

    # Defines flake.lib.mkNixos — wires a nixosConfiguration together from
    # the transposed den.aspects modules and home-manager.
    ./hosts/lib.nix

    # nire-durandal host: sets flake.nixosConfigurations."nire-durandal" and
    # declares the host-specific NixOS aspect (hostname, stateVersion, hw-conf).
    ./hosts/nire-durandal/durandal-host-config.nix
  ];
}
