# Flake outputs — receives the evaluated inputs attrset from flake.nix.
# flake.nix is auto-generated by flake-file; edit flake-config.nix and run
# `nix run .#write-flake` to regenerate it. This file is NOT auto-generated.
#
# ─── How this configuration is organised (the dendritic / aspect pattern) ────
#
# Instead of one giant configuration.nix, config is split into small focused
# files called "aspects". Each aspect declares what it contributes:
#
#   den.aspects.<name>.nixos      = { pkgs, ... }: { /* NixOS options */ };
#   den.aspects.<name>.homeManager = { pkgs, ... }: { /* HM options */   };
#
# Examples:
#   den.aspects.gaming.nixos       — Steam, game-mode, etc.
#   den.aspects.wm-kde.nixos       — KDE Plasma desktop options
#   den.aspects.firefox.homeManager — Firefox home-manager config
#
# There is no central list to update when you add a new aspect file.
# import-tree ./configs auto-discovers every .nix file in configs/ and loads
# it. A new file simply appears in the assembled config on the next rebuild.
#
# ─── How aspects become a bootable NixOS config ──────────────────────────────
#
#   1. Every .nix file under configs/ is imported (via import-tree).
#      Each file sets den.aspects.<name>.{nixos,homeManager}.
#
#   2. den-bridge.nix copies den.aspects → flake.aspects (the two libraries
#      use different namespaces and don't connect automatically).
#
#   3. flake-aspects reads flake.aspects and transposes it:
#        den.aspects.X.nixos       becomes  flake.modules.nixos.X
#        den.aspects.X.homeManager becomes  flake.modules.homeManager.X
#
#   4. hosts/lib.nix assembles flake.modules.nixos into a nixosSystem call.
#      hosts/nire-durandal/elly-home.nix does the same for home-manager.
#
#   5. durandal-host-config.nix registers the final output:
#        flake.nixosConfigurations."nire-durandal" = lib.mkNixos ...
#
# ─── Adding a new aspect ─────────────────────────────────────────────────────
#
#   Create a .nix file anywhere under configs/ with this shape:
#
#     { den.aspects.<name>.nixos = { pkgs, lib, ... }: { /* options */ }; }
#
#   That's it. import-tree will pick it up automatically.
#
# ─── Adding a new host ───────────────────────────────────────────────────────
#
#   1. Create hosts/<hostname>/<hostname>-host-config.nix
#      (declare the host aspect: hostname, stateVersion, hw-conf)
#   2. Add its architecture to system-archs.nix if new
#   3. Import the new host file in this file's imports list below
#
inputs:
inputs.flake-parts.lib.mkFlake { inherit inputs; } {
  imports = [
    # den: provides the `den.aspects` flake-parts option. Every file under
    # configs/ sets den.aspects.<name>.{nixos,homeManager} to declare its
    # piece of the configuration.
    inputs.den.flakeModule

    # flake-aspects: transposes den.aspects.X.nixos  → flake.modules.nixos.X
    #                            den.aspects.X.homeManager → flake.modules.homeManager.X
    # This transposition happens at evaluation time before NixOS sees anything,
    # so hosts/lib.nix can just read builtins.attrValues config.flake.modules.nixos.
    inputs.flake-aspects.flakeModule

    # flake-file: provides the `write-flake` app that regenerates flake.nix.
    inputs.flake-file.flakeModules.default

    # Auto-discovers and imports every .nix file under configs/.
    # This is what makes the aspect pattern zero-boilerplate: no central list.
    (inputs.import-tree ./configs)

    # Which CPU architectures this flake supports. Add a new entry here when
    # adding a host with an architecture not already listed.
    ./system-archs.nix

    # Copies den.aspects → flake.aspects so flake-aspects can see them.
    # The two libraries use separate namespaces and don't connect on their own.
    ./hosts/den-bridge.nix

    # Defines flake.lib.mkNixos, the helper used by each host to assemble
    # all aspects into a nixosSystem call.
    ./hosts/lib.nix

    # nire-durandal: host-specific aspect (hostname, stateVersion, hw-conf)
    # and the flake.nixosConfigurations."nire-durandal" output.
    ./hosts/nire-durandal/durandal-host-config.nix

    # elly's standalone home-manager configuration for nire-durandal.
    ./hosts/nire-durandal/elly-home.nix
  ];
}
