# Flake outputs — receives the evaluated inputs attrset from flake.nix.
# flake.nix is auto-generated by flake-file; edit flake-config.nix and run
# `nix run .#write-flake` to regenerate it. This file is NOT auto-generated.
inputs:
inputs.flake-parts.lib.mkFlake { inherit inputs; } {
  imports = [
    # den: provides the `den.aspects` option used throughout configs/ to declare
    # reusable NixOS/home-manager modules in a dendritic pattern.
    # lib.nix and elly-home.nix collect aspects directly from config.den.aspects —
    # no flake-aspects transposition or den includes/resolve needed.
    inputs.den.flakeModule

    # flake-file: provides the `write-flake` app that regenerates flake.nix.
    inputs.flake-file.flakeModules.default

    # Recursively imports every .nix file under configs/, picking up all
    # den.aspects declarations for system-config and home-manager.
    (inputs.import-tree ./configs)

    # Declares which CPU architectures this flake supports (x86_64-linux, aarch64-darwin).
    ./system-archs.nix

    # Defines flake.lib.mkNixos — builds a nixosConfiguration by collecting all
    # den.aspects.*.nixos modules from config.den.aspects.
    ./hosts/lib.nix

    # nire-durandal host: sets flake.nixosConfigurations."nire-durandal" and
    # declares the host-specific NixOS aspect (hostname, stateVersion, hw-conf).
    ./hosts/nire-durandal/durandal-host-config.nix

    # elly's standalone home-manager configuration for nire-durandal.
    ./hosts/nire-durandal/elly-home.nix
  ];
}
