{ lib, ... }:
    let
        moduleName = lib.removeSuffix ".nix" (baseNameOf __curPos.file);
    in {
        flake.modules.homeManager.${moduleName} = { pkgs, ... }:
            let
                # # description = "chelper/coding-helper: Z.AI's GLM Coding Plan CLI for managing multi coding tools' API keys and config"
                #
                # Not in nixpkgs, so built here from the published npm tarball
                # with buildNpmPackage rather than reached for via `npx`.
                codingHelper = pkgs.buildNpmPackage rec {
                    pname   = "zai-coding-helper";
                    version = "0.1.0-beta.1";

                    src = pkgs.fetchurl {
                        url  = "https://registry.npmjs.org/@z_ai/coding-helper/-/coding-helper-${version}.tgz";
                        hash = "sha512-gPihKcScNotQ1+XgtmmCJRYZnmxzT+QNRq2px+cn32PI+je34MRXqrt+YHYCi4YN0dfBmufzKLN1FbiJzqrOAA==";
                    };

                    # `npm pack` doesn't include a package-lock.json in the
                    # published tarball, so both files here were generated by
                    # hand and are committed alongside this module:
                    # zai-coding-helper-package.json and
                    # zai-coding-helper-package-lock.json.
                    #
                    # Both have devDependencies stripped: upstream's
                    # devDependencies (eslint, typescript, tsx, nodemon, ...)
                    # resolve to ~130 extra packages that are never used here,
                    # because dist/ is already built in the published tarball
                    # and this derivation never runs `npm run build`. A
                    # lockfile generated the ordinary way (full graph,
                    # devDependencies included) was ~3000 lines for that
                    # reason; this one is ~950.
                    #
                    # package.json needs the same treatment as the lock file,
                    # not just the lock file alone: `npm ci` cross-checks
                    # package.json's *declared* devDependencies against the
                    # lock file even when they won't be installed, and errors
                    # ("Missing: eslint@... from lock file") if they're
                    # declared but absent from a trimmed lock.
                    #
                    # Both files are `cp`'d in via postPatch rather than
                    # edited in place with e.g. a `node -e` one-liner: this
                    # postPatch is replayed verbatim inside the separate,
                    # minimal fixed-output derivation buildNpmPackage uses to
                    # fetch npmDepsHash's contents, which has no `node` on its
                    # PATH -- only `cp` is guaranteed there.
                    postPatch = ''
                        cp ${./zai-coding-helper-package.json} package.json
                        cp ${./zai-coding-helper-package-lock.json} package-lock.json
                    '';

                    npmDepsHash = "sha256-eB5CtRxnjzOta+nmtl/00TQThKC6GPfl1XTStTx57to=";
                    dontNpmBuild = true; # dist/ ships prebuilt in the published tarball

                    meta = {
                        description = "CLI for managing Z.AI's GLM Coding Plan across multiple coding tools (Claude Code, etc)";
                        homepage    = "https://docs.z.ai/";
                        mainProgram = "chelper";
                    };
                };
            in {
                home.packages = [
                    codingHelper
                ];
            };
}
