# nire-durandal host configuration
#
# This file does two things:
#
#   1. Registers the NixOS output:
#        flake.nixosConfigurations."nire-durandal" = lib.mkNixos ...
#      This is what makes `nixos-rebuild --flake .#nire-durandal` work.
#
#   2. Declares the host-specific aspect:
#        den.aspects."nire-durandal".nixos = { ... }: { ... }
#      This aspect sets the options that are specific to this machine —
#      hostname, stateVersion, hardware config — things that would be wrong
#      to put in a shared aspect that all hosts receive.
#
# All other aspects (gaming, sound, kde, …) live under configs/system-config/
# and are picked up automatically. This file only declares what makes
# nire-durandal different from every other machine.
#
# To add a new host:
#   Copy this file to hosts/<new-host>/<new-host>-host-config.nix,
#   update the names, point hw-conf at the new hardware-configuration.nix,
#   and add the new file to outputs.nix imports.
{ inputs, ... }:
{
  # Register this host as a flake output.
  # `lib.mkNixos` (defined in hosts/lib.nix) assembles ALL nixos aspects
  # from configs/ plus this host aspect into a single nixosSystem call.
  flake.nixosConfigurations."nire-durandal" = inputs.self.lib.mkNixos "x86_64-linux" "nire-durandal";

  # The host aspect: machine-specific NixOS options.
  # `nix-index-database` arrives via specialArgs = inputs (set in lib.nix),
  # which passes all flake inputs as extra arguments to every NixOS module.
  den.aspects."nire-durandal".nixos =
    { nix-index-database, ... }:
    {
      nixpkgs.hostPlatform = "x86_64-linux";
      system.stateVersion = "23.11"; # Don't change. https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion
      networking.hostName = "nire-durandal";

      imports = [
        nix-index-database.nixosModules.nix-index
        # hw-conf/ contains the hardware-configuration.nix generated by nixos-generate-config.
        # fixes/ contains any hardware-specific patches or workarounds.
        (inputs.import-tree ./hw-conf)
        (inputs.import-tree ./fixes)
      ];
    };
}
