# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/380C-3C39";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };



  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a99ae3fe-3254-4d6b-9da7-c448a89d166d";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/03b8f5c0-d846-4fde-b533-2a22e8e9975b";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a99ae3fe-3254-4d6b-9da7-c448a89d166d";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=home" ];
      
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a99ae3fe-3254-4d6b-9da7-c448a89d166d";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "compress=zstd" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/a99ae3fe-3254-4d6b-9da7-c448a89d166d";
      fsType = "btrfs";
      options = [ "subvol=persist" "noatime" "compress=zstd" ];
      neededForBoot = true; 
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/a99ae3fe-3254-4d6b-9da7-c448a89d166d";
      fsType = "btrfs";
      options = [ "subvol=log" "noatime" "compress=zstd" ];
      neededForBoot = true;
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
