#! /usr/bin/env bash
# Write a host's hardware-configuration.nix as a *flake-parts* module.
#
#   new-host-hardware.sh <host>            # generate on this machine
#   new-host-hardware.sh <host> hw.nix     # wrap a config generated elsewhere
#   new-host-hardware.sh <host> -          # ... or read it from stdin
#
# This exists to make one specific mistake impossible. Dropping raw
# `nixos-generate-config` output into modules/ leaves a plain NixOS module in
# the import-tree path; flake-parts then tries to resolve its `modulesPath`
# argument through its own _module.args and the whole flake dies with
# "infinite recursion encountered" -- every host, every output. That has
# happened twice here, most recently in 9fa44b2, fixed in 922289e.
set -euo pipefail

host=${1:-}
src=${2:-}
if [[ -z ${host} ]]; then
    echo "usage: new-host-hardware.sh <host> [hardware-configuration.nix|-]" >&2
    exit 2
fi

script_dir=$(cd -- "$(dirname -- "$0")" && pwd)
flake_dir=$(dirname -- "${script_dir}")
dir=${flake_dir}/modules/hosts/${host}
file=${dir}/hardware-configuration.nix

if [[ -e ${file} ]]; then
    echo "new-host-hardware.sh: ${file#"${flake_dir}"/} already exists; move it aside first" >&2
    exit 1
fi

# The source is an explicit argument rather than something inferred from
# whether stdin is a tty: under `just` stdin is neither a tty nor closed, so
# tty-sniffing either blocks on cat or silently reads nothing.
if [[ -n ${src} ]]; then
    if [[ ${src} == "-" ]]; then
        raw=$(cat)
    elif [[ -r ${src} ]]; then
        raw=$(cat -- "${src}")
    else
        echo "new-host-hardware.sh: cannot read '${src}'" >&2
        exit 1
    fi
elif command -v nixos-generate-config >/dev/null; then
    raw=$(nixos-generate-config --show-hardware-config)
else
    echo "new-host-hardware.sh: no source given and nixos-generate-config is not available." >&2
    echo "Run this on the target NixOS machine, or pass a config generated there:" >&2
    echo "  just new-host-hardware ${host} hardware-configuration.nix" >&2
    exit 1
fi

if [[ -z ${raw} ]]; then
    echo "new-host-hardware.sh: hardware config is empty" >&2
    exit 1
fi
if ! grep -q 'modulesPath' <<<"${raw}"; then
    echo "warning: input does not mention modulesPath; is it really a hardware config?" >&2
fi

# Indent the original body by four spaces so the wrapper reads as one module.
body=$(sed 's/^./    &/' <<<"${raw}")

mkdir -p "${dir}"
{
    echo "# Generated by nixos-generate-config, then wrapped as a flake-parts module."
    echo "# Do not un-wrap this: a bare NixOS module under modules/ breaks the whole"
    echo "# flake with an infinite recursion on modulesPath. See CLAUDE.md."
    echo "{ ... }:"
    echo "{"
    echo "    flake.modules.nixos.${host}Hardware ="
    echo "${body}"
    echo "    ;"
    echo "}"
} >"${file}"

echo "created ${file#"${flake_dir}"/}"
echo "  module name: flake.modules.nixos.${host}Hardware"
echo
echo "next:"
echo "  git add ${file#"${flake_dir}"/}      # nix cannot see untracked files"
echo "  reference it from the host config, e.g."
echo "      imports = with config.flake.modules.nixos; [ desktop ${host}Hardware ];"
echo "  just check"
